export const STORAGE_KEY_SESSION = 'session_token'
export const STORAGE_KEY_THEME = 'file-manager-theme'
export const THEME_CLASS_CYBER = 'cyber'
export const THEME_VALUE_CYBER = 'cyber'
export const THEME_VALUE_LIGHT = 'light'
export const API_BASE_URL = '/api'
